### ISSUE TITLE
[TaskScheduler] Таймеры

### ISSUE THREAD

**Issue by pavel-b-novikov** [orangebyte256/nsudotnet#5]
Я правильно понимаю, что у вас таймер поднимается каждую миллисекунду и проверяет нет ли каких задач?
Этот идейно неправильно. Хуже только - запихнуть проверку в while(true)

**Comment by orangebyte256** [comment]
Нет, он просыпается когда в него кладут задачу и когда пора исполнить очередную

**Comment by pavel-b-novikov** [comment]
ммм.. слабоватое решение. не делайте так в живых проектах
